apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_ME_REPO_URL
    targetRevision: main
    path: apps/hello-nginx/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

