apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securityprofile-example
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: REPLACE_ME_REPO_URL
    targetRevision: main
    path: operators/security-profile-operator/crd/examples
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

